apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::545063701330:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::545063701330:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-90P5EQPP6MY1
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2021-08-07T18:24:03Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1179"
  uid: a1b6be02-fee0-4593-ab2f-20c37c4a488f
